tasks:
  - init: mvn install spring-boot:start spring-boot:stop

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    branches: true
vscode:
  extensions:
    - runem.lit-plugin@1.1.10:/yk3Arh4MIQ3RwIcHwbX3Q==